from jinja2 import Template

LETTER_TEMPLATE = """
# Monthly Investment Letter
**Date:** {{ date }}

## Executive Summary
This month saw activity across {{ transaction_count }} transactions. 

**Portfolio Snapshot:**

**Total Value:** ${{ "{:,.2f}".format(performance.total_value) }}

**Total Gain/Loss:** ${{ "{:,.2f}".format(performance.total_gain_loss) }} ({{ "%.2f"|format(performance.total_gain_loss_pct) }}%)

**Dividend Income:** ${{ "{:,.2f}".format(performance.total_dividends) }}

## Asset Allocation
{%- for type, value in allocation.items() %}
- **{{ type }}**: ${{ "{:,.2f}".format(value) }}
{%- endfor %}

## Portfolio Holdings Snapshot
{%- for symbol, qty in holdings.items() %}
{%- if symbol in holdings_data %}
- **{{ symbol }}**: {{ qty }} shares | Value: ${{ "{:,.2f}".format(holdings_data[symbol]['Current Value']) }} | P&L: {{ holdings_data[symbol]['Total Gain/Loss Percent'] }}%
{%- else %}
- **{{ symbol }}**: {{ qty }} shares
{%- endif %}
{%- endfor %}

## Risk & Factor Exposure
*Analysis of your current exposures based on portfolio value.*
- **Concentration**: You currently hold {{ holdings|length }} unique positions.
{%- if holdings|length < 5 %}
  - *Alert*: Portfolio appears concentrated.
{%- endif %}

### Factor Allocation (by Value)
{%- for factor, value in factors.items() %}
- **{{ factor }}**: ${{ "{:,.2f}".format(value) }}
{%- endfor %}

## Suggested Tweaks
Based on your recent activity and current structure:
{%- for tweak in tweaks %}
- [ ] {{ tweak }}
{%- else %}
- No immediate tweaks suggested. Maintain course.
{%- endfor %}

---
*Generated by Antigravity Investment Tool*
"""

def render_letter(data):
    template = Template(LETTER_TEMPLATE)
    return template.render(**data)
