from jinja2 import Template

LETTER_TEMPLATE = """
# Monthly Investment Letter
**Date:** {{ date }}

## Executive Summary
This month saw activity across {{ transaction_count }} transactions. 
Total dividend income received: ${{ "%.2f"|format(performance.total_dividends) }}.

## Portfolio Holdings Snapshot
{% for symbol, qty in holdings.items() %}
- **{{ symbol }}**: {{ qty }} shares
{% endfor %}

## Risk & Factor Exposure
*Analysis of your current exposures based on historical activity.*
- **Concentration**: You currently hold {{ holdings|length }} unique positions.
{% if holdings|length < 5 %}
  - *Alert*: Portfolio appears concentrated.
{% endif %}

### Factor Allocation (by Share Count)
{% for factor, qty in factors.items() %}
- **{{ factor }}**: {{ qty }} shares
{% endfor %}

## Suggested Tweaks
Based on your recent activity and current structure:
{% for tweak in tweaks %}
- [ ] {{ tweak }}
{% else %}
- No immediate tweaks suggested. Maintain course.
{% endfor %}

---
*Generated by Antigravity Investment Tool*
"""

def render_letter(data):
    template = Template(LETTER_TEMPLATE)
    return template.render(**data)
